### ISSUE TITLE
Upon cloning the repo and running `reset_template.m`, allow the user to set an author for the code base

### ISSUE THREAD

**Issue by HarmonicReflux** [djmaxus/matlab-repo-init#21]
After a user cloned the repository, they need to run the script `reset_template.m` where they are prompted to select a license (MIT and/or Apache 2.0 license ). The user is, however not prompted to input a username and hence the license files will always be populated with "Maksim Elizarev" to be the author. This has to be changed such that the actual author making use of the MATLAB template can set the author themselves. 

![matlab_issue](https://github.com/user-attachments/assets/72cb79e1-db2a-4af5-981f-bacd4d8d3a43)

**Comment by djmaxus** [comment]
I think I managed to fix that within #31 

Thank you very much for noticing this flaw!
