### ISSUE TITLE
Automatically keep ICL fork in sync with CI workflow

### ISSUE THREAD

**Issue by alexdewar** [djmaxus/matlab-repo-init#9]

**Comment by djmaxus** [comment]
The job run is being skipped for some reason:

https://github.com/djmaxus/matlab-repo-init/actions/workflows/sync-mirror.yml

Could the condition in the `if` statement be false?

**Comment by alexdewar** [comment]
My mistake. The `if` statement *does* look wrong. I've opened a PR which should hopefully address this: #27
